# 简化版 Docker Compose 配置
# 适用于快速部署和测试

version: '3.8'

services:
  dnf-pvf-tutorial:
    # 使用预构建的镜像
    image: ghcr.io/springandme/dnf-pvf-tutorial:latest
    
    container_name: dnf-pvf-tutorial-simple
    
    # 端口映射
    ports:
      - "7210:3000"
    
    # 挂载课程数据目录
    volumes:
      - ./pvfCourse:/app/pvfCourse:ro
    
    # 重启策略
    restart: unless-stopped
    
    # 环境变量
    environment:
      - NODE_ENV=production
