name: Docker Publish Workflow

# 当代码推送到 main 分支时触发此工作流
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # 使用最新的 Ubuntu 运行环境
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        # 检出代码，以便工作流可以访问它
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        # 使用 GITHUB_TOKEN 登录到 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        # 自动提取 Docker 镜像的标签和元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        # 构建 Docker 镜像并将其推送到 GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}